export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_ERROR = 'SIGN_UP_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const CREATE_SLOT_SUCCESS = 'CREATE_SLOT_SUCCESS';
export const CREATE_SLOT_FAIL = 'CREATE_SLOT_FAIL';
export const GET_SLOT_SUCCESS = 'GET_SLOT_SUCCESS';
export const GET_SLOT_ERROR = 'GET_SLOT_ERROR';
export const GET_ALL_WISHES_SUCCESS = 'GET_ALL_WISHES_SUCCESS';
export const GET_ALL_WISHES_ERROR = 'GET_ALL_WISHES_ERROR';
// export const GET_ALL_PENDING_WISHES_SUCCESS = 'GET_ALL_PENDING_WISHES_SUCCESS';
// export const GET_ALL_PENDING_WISHES_ERROR = 'GET_ALL_PENDING_WISHES_ERROR';
export const GET_ALL_FULFILLED_WISHES_SUCCESS = 'GET_ALL_FULFILLED_WISHES_SUCCESS';
export const GET_ALL_FULFILLED_WISHES_ERROR = 'GET_ALL_FULFILLED_WISHES_ERROR';




